### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by ansarimofid** [devists/projectile#4]
Add proper readme for Initializing project for local development.

**Comment by lalitmee** [comment]
I have created temporary readme file.

**Comment by ansarimofid** [comment]
Please close after adding appropriate readme

**Comment by anshuldawar** [comment]
added README.md

**Comment by ansarimofid** [comment]
@anshuldawar  Please commit and merge in proper way. Edit everything in local and merge only if you are sure about the commit. Don't create unnecessary commits since it makes all VCS look dirty. Hope you don't repeat it afterwards.

**Comment by anshuldawar** [comment]
@ansarimofid that was a mistake, i will not repeat that in future.
